name: Update Changelog and Publish

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Set up dart latest
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk:  stable
        id: dart
        
      - name: Run the test
        run:  M3O_API_TOKEN=$HW_TOKEN dart test .
        env:
          HW_TOKEN: ${{ secrets.HW_TOKEN }}
          
      - name: dry run dart publish
        run: |
          dart pub publish --dry-run