name: Update Changelog and Publish

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
          path: m3o-dart

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}
          path-to-changelog: '/github/workspace/m3o-dart/CHANGELOG.md'

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: publish m3o-dart package
        uses: GWT-M3O-TEST/m3o-publish-dart-action@main
        with:
          pub_credentials: ${{ secrets.PUB_CREDENTIALS }}
          